name: SwiftLint
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install SwiftLint
        run: |
          wget https://github.com/realm/SwiftLint/releases/download/0.57.0/swiftlint_linux.zip
          unzip swiftlint_linux.zip
          sudo mv swiftlint /usr/local/bin/
          sudo chmod +x /usr/local/bin/swiftlint

      - name: SwiftLint
        run: swiftlint lint
        continue-on-error: true
